name : Terraform-Workflow

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feature/CI

jobs:
  build:
    name: Infra Setup
    runs-on : ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  

      - name: installing terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest