name : Terraform-Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Infra Setup
    runs-on : ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  

      - name: installing terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.10.5

      # - name: Format Terraform
      #   run: terraform fmt

      # - name: Validate Terraform
      #   run: terraform validate