name : Terraform-Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Infra Setup 
    runs-on : ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest
      
      - name: Terraform Initialization
        run: terraform init
      
      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validation
        run: terraform validate